### ISSUE TITLE
Readme - error no link to shorten tools source

### ISSUE THREAD

**Issue by wrapperband** [Thoulah/convtoflac#1]
Shorten - requires shorten binary : http://www.etree.org/shnutils/shorten/

Is no longer valid, can you push a copy?

**Comment by YiiRocks** [comment]
The shorten project has been abondoned. I can't find any active official website. Even [Wikipedia](https://en.wikipedia.org/wiki/Shorten_(file_format)) links to the defunct page.

**Comment by YiiRocks** [comment]
https://web.archive.org/web/20180903155129/http://www.etree.org/shnutils/shorten/
